/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Data.IMesto;
import Data.ISilnice;
import Data.Mesto;
import Data.Silnice;
import java.awt.Point;
import javax.swing.JOptionPane;

/**
 *
 * @author George
 */
public class PridejSilnici extends javax.swing.JPanel {

    private IMesto mestoDo, mestoOd;
    private boolean pristupno;

    /**
     * Creates new form PridejSilnici
     */
    public PridejSilnici() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNazevSilnice = new javax.swing.JTextField();
        txtMesoOd = new javax.swing.JTextField();
        txtMestoDo = new javax.swing.JTextField();
        txtSouradniceOd = new javax.swing.JTextField();
        txtSouradniceDo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comBoxUzavreno = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtOhodnoceni = new javax.swing.JTextField();

        jLabel1.setText("Název silnice : ");

        jLabel2.setText("Město od : ");

        jLabel3.setText("Město do : ");

        jLabel4.setText("Souřadnice města od : ");

        jLabel5.setText("Souřadnice města do : ");

        jLabel6.setText("Otevreno :");

        comBoxUzavreno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano", "Ne" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Přidej Silnici");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Odeber Silnici");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Nastav Silnici");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Ohodnoceni : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSouradniceDo, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(txtSouradniceOd, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(txtMestoDo, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(txtMesoOd, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(txtNazevSilnice)
                                .addComponent(comBoxUzavreno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtOhodnoceni))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtOhodnoceni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazevSilnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMesoOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMestoDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSouradniceOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSouradniceDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comBoxUzavreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean vlozeno = false;
        if (txtNazevSilnice.getText() != null) {
            if (txtMesoOd.getText() != null) {
                if (txtMestoDo.getText() != null) {
                    IMesto mesto1 = new Mesto(txtMesoOd.getText().toString(), null);
                    IMesto mesto2 = new Mesto(txtMestoDo.getText().toString(), null);

                    mestoOd = GUISemA.mapa.najdiMesto(mesto1);
                    mestoDo = GUISemA.mapa.najdiMesto(mesto2);

                    if (mestoOd == null && mestoDo == null) {
                        return;
                    }
                    ISilnice silnice;
                    boolean uzavreno = false;
                    switch (comBoxUzavreno.getSelectedIndex()) {
                        case 1:
                            uzavreno = true;
                            break;
                        case 2:
                            uzavreno = false;
                            break;

                    }

                    silnice = new Silnice(Integer.valueOf(txtOhodnoceni.getText().toString()), uzavreno, txtNazevSilnice.getText().toString(), mestoOd, mestoDo);
                    if (silnice != null) {
                        GUISemA.mapa.pridejHranu(mestoOd, mestoDo, silnice);
                        vlozeno = true;
                    }
                    if (vlozeno == true) {
                        jTextArea1.append("Vlozeno");
                    } else {
                        jTextArea1.append("Nepodarilo se vlozit");
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        IMesto pom = new Mesto(txtMesoOd.getText(), null);
        IMesto pom2 = new Mesto(txtMestoDo.getText(), null);
        ISilnice silnice;
        boolean odebrano = false;
        silnice = GUISemA.mapa.smazSilnici(pom, pom2);
        if (silnice != null) {
            jTextArea1.append("Silnice odebrana : " + silnice.toString() + "\n");
        } else {
            JOptionPane.showMessageDialog(this, "Silnice nebyla nalezena");
        }
    }

    private boolean uzavreno(int i) {
        switch (i) {
            case 0:
                return false;
            default:
                return true;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        IMesto pom = new Mesto(txtMesoOd.getText(), null);
        IMesto pom2 = new Mesto(txtMestoDo.getText(), null);
        IMesto mestoOd = GUISemA.mapa.najdiMesto(pom);
        IMesto mestoDo = GUISemA.mapa.najdiMesto(pom2);
        boolean uzavreno = false;
        switch (comBoxUzavreno.getSelectedIndex()) {
            case 1:
                uzavreno = true;
                break;
            case 2:
                uzavreno = false;
                break;

        }
        ISilnice silnice = new Silnice(Integer.valueOf(txtOhodnoceni.getText().toString()), uzavreno, txtNazevSilnice.getText().toString(), mestoOd, mestoDo);

        silnice = GUISemA.mapa.upravSilnic(mestoOd, mestoDo, silnice);
        if (silnice != null) {
            jTextArea1.append("Silnice Upravena : " + silnice.toString() + "\n");
        } else {
            JOptionPane.showMessageDialog(this, "Silnice nebyla nalezena");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comBoxUzavreno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtMesoOd;
    private javax.swing.JTextField txtMestoDo;
    private javax.swing.JTextField txtNazevSilnice;
    private javax.swing.JTextField txtOhodnoceni;
    private javax.swing.JTextField txtSouradniceDo;
    private javax.swing.JTextField txtSouradniceOd;
    // End of variables declaration//GEN-END:variables
}
