/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Data.Mesto;
import java.util.LinkedList;
import java.util.Queue;

/**
 *
 * @author George
 */
public class StromVypis extends javax.swing.JPanel {

    public StromVypis(Mesto v) {
        initComponents();
        areaStrom.append(vypis(v));
    }
    public String vypis(Mesto vychozi){
    int w = getWidth();
    int h= getHeight();
    String ret = "";
        Queue<String> seznam = new LinkedList();
        seznam.add(GUISemA.mapa.najdiMesto(vychozi).getKey());
        seznam.add("|");
        seznam.add("\n");
        while (!seznam.isEmpty()) {
            String s = seznam.poll();
            switch (s) {
                case "|":
                    ret += "    "+s+"   ";
//                    areaStrom.append(ret);
                    break;
                case "\n":
                    ret += "  "+s+"  ";
//                    areaStrom.append(ret);
                    if (seznam.size() > 1) {
                        seznam.add(s);
                    }
                    break;
                default:
                    ret += s + ", ";
//                    areaStrom.append(ret);
                    Mesto pom = (Mesto) GUISemA.mapa.najdiMesto(new Mesto(s, null));
                    for (String str : pom.getNasledniky()) {
                        seznam.add(str);
                    }
                    seznam.add("|");
                    break;
            }
        }
        return ret;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaStrom = new javax.swing.JTextArea();

        areaStrom.setColumns(20);
        areaStrom.setRows(5);
        jScrollPane1.setViewportView(areaStrom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaStrom;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
